baseurl: "/peoples-guide"
layout: default

defaults:
  - scope:
      path: ""
      type: topics
    values:
      layout: default

collections:
  topics:
    output: true
    permalink: /topics/:path/
